[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/callback"
  status = 200
  force = true
  conditions = { HttpMethod = ["POST"] }